# Generated by Django 3.0 on 2022-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp_in', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-03-26'),
            preserve_default=False,
        ),
    ]
